
CREATE TYPE "Role" AS ENUM ('OWNER','SCHOOL_ADMIN','CLASS_TEACHER','SUBJECT_TEACHER','PARENT');
CREATE TYPE "UserStatus" AS ENUM ('ACTIVE','INACTIVE','RESTRICTED');
CREATE TYPE "TeacherType" AS ENUM ('CLASS_TEACHER','SUBJECT_TEACHER');
CREATE TYPE "AttendanceStatus" AS ENUM ('PRESENT','ABSENT','LATE');
CREATE TYPE "PaymentVerification" AS ENUM ('PENDING','VERIFIED','REJECTED');

CREATE TABLE "User"(id TEXT PRIMARY KEY,name TEXT NOT NULL,email TEXT UNIQUE,mobile TEXT UNIQUE,"passwordHash" TEXT NOT NULL,role "Role" NOT NULL,status "UserStatus" NOT NULL DEFAULT 'ACTIVE',"mustChangePassword" BOOLEAN NOT NULL DEFAULT true,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "SchoolClass"(id TEXT PRIMARY KEY,"className" TEXT NOT NULL,section TEXT NOT NULL,"academicYear" TEXT NOT NULL,"classTeacherId" TEXT UNIQUE);
CREATE TABLE "Subject"(id TEXT PRIMARY KEY,name TEXT NOT NULL,code TEXT UNIQUE NOT NULL,"maximumMarks" INTEGER NOT NULL DEFAULT 100);
CREATE TABLE "Teacher"(id TEXT PRIMARY KEY,"userId" TEXT UNIQUE NOT NULL,"employeeId" TEXT UNIQUE NOT NULL,"teacherType" "TeacherType" NOT NULL,"assignedClassId" TEXT UNIQUE,"assignedSubjectId" TEXT,department TEXT,qualification TEXT,"joiningDate" TIMESTAMP(3),mobile TEXT,email TEXT,"accountStatus" TEXT NOT NULL DEFAULT 'Allowed');
CREATE TABLE "Student"(id TEXT PRIMARY KEY,"studentId" TEXT UNIQUE NOT NULL,name TEXT NOT NULL,"rollNumber" TEXT,"dateOfBirth" TIMESTAMP(3),gender TEXT,email TEXT,"parentMobile" TEXT,house TEXT,"classId" TEXT,"academicYear" TEXT,status TEXT NOT NULL DEFAULT 'Active',photo TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "Parent"(id TEXT PRIMARY KEY,"userId" TEXT UNIQUE NOT NULL,name TEXT NOT NULL,mobile TEXT,email TEXT);
CREATE TABLE "ParentStudent"("parentId" TEXT NOT NULL,"studentId" TEXT NOT NULL,PRIMARY KEY("parentId","studentId"));
CREATE TABLE "Attendance"(id TEXT PRIMARY KEY,"studentId" TEXT NOT NULL,"classId" TEXT NOT NULL,date TIMESTAMP(3) NOT NULL,period TEXT,status "AttendanceStatus" NOT NULL,"markedBy" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "Homework"(id TEXT PRIMARY KEY,"subjectId" TEXT NOT NULL,"teacherId" TEXT NOT NULL,"classId" TEXT NOT NULL,title TEXT NOT NULL,description TEXT,topics TEXT,questions TEXT,"assignedDate" TIMESTAMP(3) NOT NULL,"dueDate" TIMESTAMP(3) NOT NULL,priority TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "HomeworkSubmission"(id TEXT PRIMARY KEY,"homeworkId" TEXT NOT NULL,"studentId" TEXT NOT NULL,submission TEXT,attachment TEXT,status TEXT NOT NULL DEFAULT 'Submitted',"submittedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "Mark"(id TEXT PRIMARY KEY,"studentId" TEXT NOT NULL,"subjectId" TEXT NOT NULL,"classId" TEXT NOT NULL,exam TEXT NOT NULL,"maximumMarks" INTEGER NOT NULL,"obtainedMarks" INTEGER NOT NULL,"enteredBy" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "Timetable"(id TEXT PRIMARY KEY,"classId" TEXT NOT NULL,"subjectId" TEXT NOT NULL,"teacherId" TEXT NOT NULL,day TEXT NOT NULL,period TEXT NOT NULL,"startTime" TEXT NOT NULL,"endTime" TEXT NOT NULL);
CREATE TABLE "Notice"(id TEXT PRIMARY KEY,title TEXT NOT NULL,description TEXT NOT NULL,audience TEXT NOT NULL,"createdBy" TEXT NOT NULL,attachment TEXT,"publishedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "Event"(id TEXT PRIMARY KEY,title TEXT NOT NULL,description TEXT,"eventDate" TIMESTAMP(3) NOT NULL,location TEXT,"createdBy" TEXT NOT NULL,media JSONB,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "Certificate"(id TEXT PRIMARY KEY,"studentId" TEXT NOT NULL,"certificateType" TEXT NOT NULL,title TEXT NOT NULL,description TEXT,"certificateFile" TEXT,"issuedDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"createdBy" TEXT NOT NULL);
CREATE TABLE "Fee"(id TEXT PRIMARY KEY,"studentId" TEXT NOT NULL,"feeType" TEXT NOT NULL,amount DECIMAL(65,30) NOT NULL,"academicYear" TEXT NOT NULL,"dueDate" TIMESTAMP(3),status TEXT NOT NULL DEFAULT 'Pending',"receiptNumber" TEXT,"paymentStatus" TEXT NOT NULL DEFAULT 'Unpaid',"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "FeeTransaction"(id TEXT PRIMARY KEY,"feeId" TEXT NOT NULL,"studentId" TEXT NOT NULL,amount DECIMAL(65,30) NOT NULL,"paymentMethod" TEXT,"transactionId" TEXT,"paymentDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"paymentProof" TEXT,"verificationStatus" "PaymentVerification" NOT NULL DEFAULT 'PENDING',"verifiedBy" TEXT,"verifiedAt" TIMESTAMP(3));
CREATE TABLE "SchoolInformation"(id TEXT PRIMARY KEY DEFAULT 'default',"schoolName" TEXT,address TEXT,"contactNumber" TEXT,email TEXT,website TEXT,"visionMission" TEXT,achievements TEXT,"administratorChairman" TEXT,principal TEXT,"vicePrincipal" TEXT,teachers TEXT,classrooms TEXT,library TEXT,"computerLab" TEXT,"scienceLab" TEXT,playground TEXT,transportation TEXT,"otherFacilities" TEXT,"studentRules" TEXT,"uniformGuidelines" TEXT,"attendancePolicy" TEXT,"disciplinePolicy" TEXT,"generalInstructions" TEXT,"googleMapsLocation" TEXT,"officeContact" TEXT,"emergencyContact" TEXT,"updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "SchoolSettings"(id TEXT PRIMARY KEY DEFAULT 'default',"schoolName" TEXT,logo TEXT,slogan TEXT,"welcomeBackground" TEXT,"academicYear" TEXT,"enabledModules" JSONB,"feePaymentEnabled" BOOLEAN NOT NULL DEFAULT true,"updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "AppState"(id TEXT PRIMARY KEY DEFAULT 'default',data JSONB NOT NULL,"updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "Notification"(id TEXT PRIMARY KEY,"studentId" TEXT,type TEXT NOT NULL,title TEXT NOT NULL,message TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"readAt" TIMESTAMP(3));
CREATE TABLE "PasswordResetToken"(id TEXT PRIMARY KEY,"userId" TEXT NOT NULL,"tokenHash" TEXT UNIQUE NOT NULL,"expiresAt" TIMESTAMP(3) NOT NULL,"usedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX "PasswordResetToken_userId_idx" ON "PasswordResetToken"("userId");
CREATE INDEX "PasswordResetToken_expiresAt_idx" ON "PasswordResetToken"("expiresAt");
CREATE TABLE "AuditLog"(id TEXT PRIMARY KEY,"userId" TEXT,action TEXT NOT NULL,entity TEXT NOT NULL,"entityId" TEXT,"oldValue" JSONB,"newValue" JSONB,timestamp TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"ipAddress" TEXT);

CREATE UNIQUE INDEX "SchoolClass_className_section_academicYear_key" ON "SchoolClass"("className",section,"academicYear");
ALTER TABLE "PasswordResetToken" ADD CONSTRAINT "PasswordResetToken_userId_fkey" FOREIGN KEY("userId") REFERENCES "User"(id) ON DELETE CASCADE;
ALTER TABLE "Parent" ADD CONSTRAINT "Parent_userId_fkey" FOREIGN KEY("userId") REFERENCES "User"(id) ON DELETE CASCADE;
ALTER TABLE "Teacher" ADD CONSTRAINT "Teacher_userId_fkey" FOREIGN KEY("userId") REFERENCES "User"(id) ON DELETE CASCADE;
ALTER TABLE "Teacher" ADD CONSTRAINT "Teacher_assignedClassId_fkey" FOREIGN KEY("assignedClassId") REFERENCES "SchoolClass"(id) ON DELETE SET NULL;
ALTER TABLE "Teacher" ADD CONSTRAINT "Teacher_assignedSubjectId_fkey" FOREIGN KEY("assignedSubjectId") REFERENCES "Subject"(id) ON DELETE SET NULL;
ALTER TABLE "SchoolClass" ADD CONSTRAINT "SchoolClass_classTeacherId_fkey" FOREIGN KEY("classTeacherId") REFERENCES "Teacher"(id) ON DELETE SET NULL;
ALTER TABLE "Student" ADD CONSTRAINT "Student_classId_fkey" FOREIGN KEY("classId") REFERENCES "SchoolClass"(id) ON DELETE SET NULL;
ALTER TABLE "ParentStudent" ADD CONSTRAINT "ParentStudent_parentId_fkey" FOREIGN KEY("parentId") REFERENCES "Parent"(id) ON DELETE CASCADE;
ALTER TABLE "ParentStudent" ADD CONSTRAINT "ParentStudent_studentId_fkey" FOREIGN KEY("studentId") REFERENCES "Student"(id) ON DELETE CASCADE;
ALTER TABLE "Attendance" ADD CONSTRAINT "Attendance_studentId_fkey" FOREIGN KEY("studentId") REFERENCES "Student"(id) ON DELETE CASCADE;
ALTER TABLE "Attendance" ADD CONSTRAINT "Attendance_classId_fkey" FOREIGN KEY("classId") REFERENCES "SchoolClass"(id) ON DELETE CASCADE;
ALTER TABLE "Attendance" ADD CONSTRAINT "Attendance_markedBy_fkey" FOREIGN KEY("markedBy") REFERENCES "Teacher"(id) ON DELETE RESTRICT;
ALTER TABLE "Homework" ADD CONSTRAINT "Homework_subjectId_fkey" FOREIGN KEY("subjectId") REFERENCES "Subject"(id);
ALTER TABLE "Homework" ADD CONSTRAINT "Homework_teacherId_fkey" FOREIGN KEY("teacherId") REFERENCES "Teacher"(id);
ALTER TABLE "Homework" ADD CONSTRAINT "Homework_classId_fkey" FOREIGN KEY("classId") REFERENCES "SchoolClass"(id);
ALTER TABLE "HomeworkSubmission" ADD CONSTRAINT "HomeworkSubmission_homeworkId_fkey" FOREIGN KEY("homeworkId") REFERENCES "Homework"(id) ON DELETE CASCADE;
ALTER TABLE "HomeworkSubmission" ADD CONSTRAINT "HomeworkSubmission_studentId_fkey" FOREIGN KEY("studentId") REFERENCES "Student"(id) ON DELETE CASCADE;
ALTER TABLE "Mark" ADD CONSTRAINT "Mark_studentId_fkey" FOREIGN KEY("studentId") REFERENCES "Student"(id) ON DELETE CASCADE;
ALTER TABLE "Mark" ADD CONSTRAINT "Mark_subjectId_fkey" FOREIGN KEY("subjectId") REFERENCES "Subject"(id);
ALTER TABLE "Mark" ADD CONSTRAINT "Mark_classId_fkey" FOREIGN KEY("classId") REFERENCES "SchoolClass"(id);
ALTER TABLE "Mark" ADD CONSTRAINT "Mark_enteredBy_fkey" FOREIGN KEY("enteredBy") REFERENCES "Teacher"(id) ON DELETE RESTRICT;
ALTER TABLE "Timetable" ADD CONSTRAINT "Timetable_classId_fkey" FOREIGN KEY("classId") REFERENCES "SchoolClass"(id) ON DELETE CASCADE;
ALTER TABLE "Timetable" ADD CONSTRAINT "Timetable_subjectId_fkey" FOREIGN KEY("subjectId") REFERENCES "Subject"(id);
ALTER TABLE "Timetable" ADD CONSTRAINT "Timetable_teacherId_fkey" FOREIGN KEY("teacherId") REFERENCES "Teacher"(id);
ALTER TABLE "Certificate" ADD CONSTRAINT "Certificate_studentId_fkey" FOREIGN KEY("studentId") REFERENCES "Student"(id) ON DELETE CASCADE;
ALTER TABLE "Fee" ADD CONSTRAINT "Fee_studentId_fkey" FOREIGN KEY("studentId") REFERENCES "Student"(id) ON DELETE CASCADE;
ALTER TABLE "FeeTransaction" ADD CONSTRAINT "FeeTransaction_feeId_fkey" FOREIGN KEY("feeId") REFERENCES "Fee"(id) ON DELETE CASCADE;
ALTER TABLE "FeeTransaction" ADD CONSTRAINT "FeeTransaction_studentId_fkey" FOREIGN KEY("studentId") REFERENCES "Student"(id) ON DELETE CASCADE;
ALTER TABLE "Notification" ADD CONSTRAINT "Notification_studentId_fkey" FOREIGN KEY("studentId") REFERENCES "Student"(id) ON DELETE CASCADE;
ALTER TABLE "AuditLog" ADD CONSTRAINT "AuditLog_userId_fkey" FOREIGN KEY("userId") REFERENCES "User"(id) ON DELETE SET NULL;
